# Generated by Django 3.2.6 on 2021-10-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
